name: metadata file schema
example: Please check https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/METADATA.md
desc: This is the schema of the metadata file, please refer to https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/METADATA.md for more info.
type: map
mapping:
    'team_name':
        required: True
        example: Team name is a MUST
    'model_name':
        required: True
        type: str
    'model_abbr':
        required: True
        type: str
        range:
            max: 31
        pattern: ^[a-zA-Z0-9_+]+-[a-zA-Z0-9_+]+$
    'model_version':
        required: True
        type: str
    'model_contributors':
        required: True
        type: str
    'website_url':
        required: True
        type: str
        pattern: ((http|https)\:\/\/)?[a-zA-Z0-9\.\/\?\:@\-_=#]+\.([a-zA-Z]){2,6}([a-zA-Z0-9\.\&\/\?\:@\-_=#])*
    'license':
        required: True
        type: str
    'methods':
        required: True
        type: str
        range:
            max: 200
    'modeling_NPI':
        required: True
        type: str
    'compliance_NPI':
        required: True
        type: str
    'contact_tracing':
        required: True
        type: str
    'testing':
        required: True
        type: str
    'vaccine_efficacy_delay':
        required: True
        type: str
    'vaccine_hesitancy':
        required: True
        type: str
    'vaccine_immunity_duration':
        required: True
        type: str
    'nature_immunity_duration':
        required: True
        type: str
    'case_fatality_rate':
        required: True
        type: str
        pattern: 0.\d*|1\.0?|Not applicable
    'infection_fatality_rate':
        required: True
        type: str
        pattern: 0.\d*|1\.0?|Not applicable
    'asymptomatics':
        required: True
        type: str
        pattern: 0.\d*|1\.0?|Not applicable
    'age_groups':
        required: True
        type: str
        pattern: ^(\[)([\d\-,\+]*[ \]]){1,}|Not applicable
    'importations':
        required: True
        type: str
    'confidence_interval_method':
        required: True
        type: str
    'calibration':
        required: True
        type: str
    'spatial_structure':
        required: True
        type: str
    'citation':
        type: str
    'team_funding':
        type: str
    'data_inputs':
        type: str
    'methods_long':
        type: str
        
